// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb14eIEUOIiTx-E-aPyNxmyUw1C0RIonM',
    appId: '1:56958658169:web:97139ded554ed4da3c56a8',
    messagingSenderId: '56958658169',
    projectId: 'medistore-5d38d',
    authDomain: 'medistore-5d38d.firebaseapp.com',
    storageBucket: 'medistore-5d38d.appspot.com',
    measurementId: 'G-KJBMJ3CBM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkTDc5_wvq0O662HwMVfI7ct6_7gssdw',
    appId: '1:56958658169:android:9b31b583b919a5633c56a8',
    messagingSenderId: '56958658169',
    projectId: 'medistore-5d38d',
    storageBucket: 'medistore-5d38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4BVsxNRh6RlS-UdICCo8UBR8k2Clybtc',
    appId: '1:56958658169:ios:f84dc6f97f7141983c56a8',
    messagingSenderId: '56958658169',
    projectId: 'medistore-5d38d',
    storageBucket: 'medistore-5d38d.appspot.com',
    iosBundleId: 'com.example.medistore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4BVsxNRh6RlS-UdICCo8UBR8k2Clybtc',
    appId: '1:56958658169:ios:f84dc6f97f7141983c56a8',
    messagingSenderId: '56958658169',
    projectId: 'medistore-5d38d',
    storageBucket: 'medistore-5d38d.appspot.com',
    iosBundleId: 'com.example.medistore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb14eIEUOIiTx-E-aPyNxmyUw1C0RIonM',
    appId: '1:56958658169:web:9381ec3f993228433c56a8',
    messagingSenderId: '56958658169',
    projectId: 'medistore-5d38d',
    authDomain: 'medistore-5d38d.firebaseapp.com',
    storageBucket: 'medistore-5d38d.appspot.com',
    measurementId: 'G-4773C4X193',
  );
}
